//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogDBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int C_id { get; set; }
        public string text { get; set; }
        public int rating { get; set; }
        public System.DateTime date { get; set; }
        public int publication { get; set; }
        public int user { get; set; }
    
        public virtual publications publications { get; set; }
        public virtual users users { get; set; }
    }
}
