//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogDBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public int sender { get; set; }
        public int receiver { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public string text { get; set; }
    
        public virtual users users { get; set; }
    }
}
