//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogDBApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class blogDataBaseEntities : DbContext
    {
        public blogDataBaseEntities()
            : base("name=blogDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<publications> publications { get; set; }
        public virtual DbSet<themes> themes { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
