//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogDBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publications()
        {
            this.comments = new HashSet<comments>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public int rating { get; set; }
        public System.DateTime date { get; set; }
        public int user { get; set; }
        public int theme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        public virtual themes themes { get; set; }
        public virtual users users { get; set; }
    }
}
